services:
  discordcash:
    image: ghcr.io/jayscentco/discordcash:latest
    ports:
      - "8090:8090"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - TIP_EMOJI=${TIP_EMOJI}
      - DEFAULT_TIP_AMOUNT=${DEFAULT_TIP_AMOUNT}
      - MOCK_MODE=${MOCK_MODE}
      - MIN_WITHDRAW=${MIN_WITHDRAW}
    restart: unless-stopped
